pipeline {
  agent {
    kubernetes {
      yaml '''
kind: Pod
metadata:
  name: helm
spec:
  serviceAccountName: jenkins
  containers:
  - name: helm
    image: registry.crazyzone.be/helm:latest
    imagePullPolicy: Always
    command:
    - sleep
    - infinity
'''
    }

  }
  stages {
    stage('Checking out helm branch') {
      steps {
        sh 'mkdir -p helm-docs container-home-docs'
        dir('deps') {
            checkout resolveScm(source: git('https://github.com/nvanlaerebeke/helm-docs.git'), targets: [BRANCH_NAME, 'master'])
            checkout resolveScm(source: git('https://github.com/nvanlaerebeke/container-home-docs.git'), targets: [BRANCH_NAME, 'master'])
        }
        sh 'ln -s ./deps/helm-docs ./helm-docs/'
        sh 'ln -s ./deps/container-home-docs container-home-docs'
      }
    }
    stage('build') {
      steps {
        container(name: 'helm') {
          sh '''#!/bin/sh
/build.sh release docs home
          '''
        }
      }
    }
  }
}
